### ISSUE TITLE
Sedes / Al borrar localidad, las escuelas que tienen esa localidad asignada se desaparecen

### ISSUE THREAD

**Issue by Davidperezjpa** [betolabrada/facilitadores-axios#15]
http://localhost/facilitadores-axios/admin/admin_sedes.php
Sedes / Al borrar localidad, las escuelas que tienen esa localidad asignada se pierde visualmente (deberia salir como localidad sin asignar, aun asi en la base de datos si esta la escuela)

![image](https://user-images.githubusercontent.com/38264666/89682306-20904b00-d8bc-11ea-8702-30a88bc1e25f.png)

**Comment by ArgaAlan** [comment]
Esto no debería ser un issue, ya que sí eliminas una localidad tiene lógica que las escuelas presente en ella ya no se encuentren en la db.

**Comment by betolabrada** [comment]
pero hay que setearlas a null por lo menos, alguien lo está haciendo?

**Comment by Davidperezjpa** [comment]
> pero hay que setearlas a null por lo menos, alguien lo está haciendo?

simon, ya lo hice
