### ISSUE TITLE
Escuelas no se puede borrar

### ISSUE THREAD

**Issue by Davidperezjpa** [betolabrada/facilitadores-axios#16]
http://localhost/facilitadores-axios/admin/admin_datos_escuela.php?idEscuela=18

![image](https://user-images.githubusercontent.com/38264666/89682624-a44a3780-d8bc-11ea-89d4-1e7f2da66429.png)

**Comment by ArgaAlan** [comment]
Se estaba llamando al borrado con el nombre de la escuela en lugar del ID, eso se acaba de solucionar.
